POST http://localhost:3000/users/usersetup
Content-Type: application/json

{
    "email" : "Leonard12345",
    "password" : "Hello123",
    "first_name" : "Brian",
    "last_name": "Smith",
    "status": "T"
}
