POST http://localhost:3000/addlesson
Content-Type: application/json

{
    "lessontime": "2025-04-03T12:00:00.000Z",
    "title": "my new lesson",
    "privatenotes": "yes",
    "publicnotes": "no",
    "price": "$2.00",
    "paid": true,
    "tutor_id": 22,
    "parent_id": 4,
    "clientlink": 8
}
